### ISSUE TITLE
How to programmatically scroll to Node with ScrollPane that is bound to VirtualizedScrollPane

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/Flowless#17]
I've asked this on [StackOverflow](https://stackoverflow.com/questions/34146622/how-do-scroll-to-node-using-scrollpane-that-has-hierarchical-content-and-is-bo), since that seems like the place to have that discussion. However, I am also opening an issue here because I think you, @TomasMikula , would probably be one of the few who could answer this specific question.

**Comment by TomasMikula** [comment]
Do the nodes in the `ScrollPane` have any correspondence to items in the `VirtualFlow` (assuming that the `VirtualizedScrollPane` contains a `VirtualFlow`). If so, I would bring the `VirtualFlow`'s item to the viewport using `VirtualFlow.showAsFirst(itemIndex)` and let the `ScrollPane` adjust automatically.

**Comment by JordanMartinez** [comment]
Yes and no :-D
````groovy
ScrollPane {
    HBox {
        LeafPane { // these Nodes match up with each line in StyledTextArea
            Node
            Nodes...
        }
        ParentPane { // these Nodes are unpredictable in their layout
            Node
            Nodes...
        }
        Higher ParentPanes and and their Nodes {} // unpredictable in their layout
    }

**Comment by TomasMikula** [comment]
Well, then it doesn't seem to be Flowless related. I don't know why your approach would not work. You can convert coordinates relative to a node to coordinates relative to its parent with the [localToParent](http://docs.oracle.com/javase/8/javafx/api/javafx/scene/Node.html#localToParent-double-double-) method. You will need to use it multiple times for deeper hierarchies.

**Comment by JordanMartinez** [comment]
Ok, I guess I'll have to play around it with some more.
