### ISSUE TITLE
VirtualizedScrollPane Doesn't appear in the jar

### ISSUE THREAD

**Issue by surnaturelDev** [TomasMikula/Flowless#18]
![image](https://cloud.githubusercontent.com/assets/16513804/12074733/bd14f62a-b15b-11e5-888c-31b3f22d9e4b.png)

**Comment by JordanMartinez** [comment]
Did you compile it from source?
The latest stable release doesn't include the changes that were done in the `master` branch. However, the snapshot version does include the changes.

**Comment by JordanMartinez** [comment]
Oh... I see that you posted this because of TomasMikula/RichTextFX#236...
