### ISSUE TITLE
Layout-dependent methods need to call layout() first.

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/Flowless#19]
A deficiency found in TomasMikula/RichTextFX#238.

Basic idea from Tomas:
> Methods of `VirtualFlow` whose result depends on the layout should themselves call `layout()` as the first thing. [Otherwise, the returned results aren't always valid. (I added this)] Such methods would include `getCellIfVisible`, `visibleCells` and `hit`. The fact that they first call layout() should be documented in their Javadoc.

**Comment by TomasMikula** [comment]
Thanks for tracking this.

**Comment by JordanMartinez** [comment]
You're welcome.

**Comment by TomasMikula** [comment]
Fixed by #20.
